[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pybfs"
version = "0.1.0"
description = "Python Baseflow Separation - A physically-based baseflow separation algorithm for hydrological analysis"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "BYU Hydroinformatics", email = ""}
]
keywords = ["hydrology", "baseflow", "baseflow separation", "streamflow", "groundwater"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "numpy>=1.19.0",
    "pandas>=1.1.0",
    "matplotlib>=3.3.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov>=2.0",
]

docs = [
    "mkdocs>=1.5.0",
    "mkdocs-material>=9.4.0",
    "mkdocstrings[python]>=0.24.0",
    "pymdown-extensions>=10.0",
]

[project.urls]
Homepage = "https://github.com/BYU-Hydroinformatics/pybfs"
Documentation = "https://github.com/BYU-Hydroinformatics/pybfs"
Repository = "https://github.com/BYU-Hydroinformatics/pybfs"
Issues = "https://github.com/BYU-Hydroinformatics/pybfs/issues"

[tool.setuptools]
packages = ["pybfs"]

[tool.setuptools.package-data]
pybfs = []

