# -*- coding: utf-8 -*-
"""Modified_Strict_Baseflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1To9kwJh_L7dGVgAOt08_dy9OBcIugE0E
"""

def modified_strict_baseflow(streamflow_data_series, dates_series, quantile=0.8):
    """
    Calculates the modified strict baseflow from streamflow data by integrating
    the strict baseflow identification and flow thresholding logic.

    Args:
        streamflow_data_series (np.ndarray): The streamflow time series (Q).
        dates_series (pd.Series): The corresponding date series for the streamflow data.
        quantile (float, optional): The quantile value used in strict_baseflow.
                                    Default is 0.8.

    Returns:
        tuple: A tuple containing:
            - sim (np.ndarray): The modified strict baseflow values.
            - metric_dates (np.ndarray): The dates corresponding to the modified strict baseflow.
    """

    def strict_baseflow_internal(Q, ice=None, quantile=0.8):
        dQ = (Q[2:] - Q[:-2]) / 2

        # 1. flow data associated with positive and zero values of dy / dt
        wet1 = np.concatenate([[True], dQ >= 0, [True]])

        # 2. previous 2 points before points with dy/dt≥0, as well as the next 3 points
        idx_first = np.where(wet1[1:].astype(int) - wet1[:-1].astype(int) == 1)[0] + 1
        idx_last = np.where(wet1[1:].astype(int) - wet1[:-1].astype(int) == -1)[0]
        idx_before = np.repeat([idx_first], 2) - np.tile(range(1, 3), idx_first.shape)
        idx_next = np.repeat([idx_last], 3) + np.tile(range(1, 4), idx_last.shape)
        idx_remove = np.concatenate([idx_before, idx_next])
        wet2 = np.full(Q.shape, False)
        wet2[idx_remove.clip(min=0, max=Q.shape[0] - 1)] = True

        #3
        #  recession limbs in the 80th quantile
        wet3_core = np.concatenate([[True], dQ[1:] - dQ[:-1] < 0, [True, True]])

        # Get indices where the rule is True
        idx3_all = np.where(wet3_core)[0]

        # Filter to only keep indices where flow is in the 90th percentile
        q80 = np.quantile(Q, quantile)
        idx3 = idx3_all[Q[idx3_all] >= q80]

        # Expand: remove 4 points before and 6 after each valid index
        idx3_buffer = np.repeat([idx3], 10) + np.tile(range(-4, 6), idx3.shape)

        # Clip and mark in full-length Boolean mask
        wet3 = np.full(Q.shape, False)
        wet3[idx3_buffer.clip(min=0, max=Q.shape[0] - 1)] = True

        # 4. flow data followed by a data point with a larger value of -dy / dt
        wet4 = np.concatenate([[True], dQ[1:] - dQ[:-1] < 0, [True, True]])

        # dry points, namely strict baseflow
        dry = ~(wet1+wet2+wet3+wet4)

        # avoid ice conditions which invalidate the groundwater-baseflow relationship
        if ice is not None:
            dry[ice] = False

        return dry

    def flow_thresh_internal(Q, strict_mask):
        """
        Return streamflow values where the gradient is positive
        and Q ≤ max(Q[strict_mask]).
        """
        Q = np.asarray(Q)
        Q_strict_avg = np.mean(Q[strict_mask])
        valid_indices = np.where(Q <= Q_strict_avg)[0]
        return valid_indices

    # Apply the strict baseflow identification mask using the internal function
    strict_mask = strict_baseflow_internal(streamflow_data_series, quantile=quantile)

    # Identify valid indices based on flow threshold using the internal function
    valid_indices = flow_thresh_internal(streamflow_data_series, strict_mask)

    # Combine indices from strict baseflow and flow threshold
    strict_indy = np.where(strict_mask)[0]
    combined_indy = np.union1d(valid_indices, strict_indy)

    # Extract the modified strict baseflow values and their corresponding dates
    sim = streamflow_data_series[combined_indy]
    metric_dates = dates_series.iloc[combined_indy].values

    return sim, metric_dates

def plot_streamflow_baseflow(all_dates, all_streamflow, baseflow_dates, baseflow_values, title='Streamflow and Labeled Baseflow'):
    """
    Plots the full streamflow and the identified modified strict baseflow.

    Args:
        all_dates (pd.Series): All dates in the time series.
        all_streamflow (np.ndarray): All streamflow values.
        baseflow_dates (np.ndarray): Dates corresponding to the modified strict baseflow.
        baseflow_values (np.ndarray): Values of the modified strict baseflow.
        title (str, optional): Title of the plot. Defaults to 'Streamflow and Labeled Baseflow'.
    """
    fig, ax = plt.subplots(figsize=(10, 6))

    # Plot full streamflow
    ax.plot(all_dates, all_streamflow, color='black', label='Streamflow', linewidth=1)

    # Highlight selected threshold + strict baseflow points
    ax.plot(baseflow_dates, baseflow_values, 'o', color='blue', label='Modified Strict Baseflow', markersize=5)

    # Font Sizes for Publication
    ax.set_xlabel('Date', fontsize=16)
    ax.set_ylabel('Flow (cms)', fontsize=16)
    ax.set_title(title, fontsize=18)
    ax.legend(loc='upper right', fontsize=14)
    ax.tick_params(axis='both', which='major', labelsize=14)

    # Date formatting
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())
    fig.autofmt_xdate()

    plt.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.show()

# Example
streamflow_dates = streamflow['date']
streamflow_values = streamflow['2422500'].values

# Calculate the modified strict baseflow
sim_baseflow, metric_dates_baseflow = modified_strict_baseflow(streamflow_values, streamflow_dates)

# Plot the streamflow and modified strict baseflow
plot_streamflow_baseflow(streamflow_dates, streamflow_values, metric_dates_baseflow, sim_baseflow, title='Streamflow and Labeled Baseflow for 2422500')